CREATE DATABASE PAYTOLLAPP

USE PAYTOLLAPP

-- TABLAS

CREATE TABLE PEAJE (
    ID_PEAJE INT NOT NULL,
    NOMBRE_PEAJE VARCHAR(40) NOT NULL,
    UBICACION VARCHAR(30) NOT NULL,
    TEL_PEAJE INT NOT NULL,
    CORREO_PEAJE VARCHAR(30) NOT NULL,
    NIT VARCHAR(30) NOT NULL
);

CREATE TABLE USUARIO (
    ID_USUARIO INT NOT NULL,
    NOMBRES_USUARIO VARCHAR(30) NOT NULL,
    APELLIDOS_USUARIO VARCHAR(30) NOT NULL,
	CEDULA INT NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    CORREO VARCHAR(40) NOT NULL,
    PASSWORD NVARCHAR(50) NOT NULL,
	ROL VARCHAR(30) NOT NULL
);

CREATE TABLE TARIFA (
    ID_TARIFA INT NOT NULL,
    MONTO_TARIFA INT NOT NULL,
    TRF_DESCRIPCION VARCHAR(40)
);

CREATE TABLE TARJETAHB (
    ID_TARJETAHB INT NOT NULL,
	ID_USUARIO INT NOT NULL,
    FECHA_EXP DATETIME NOT NULL,
	MODOS_RECARGA VARCHAR(30),
    SALDO INT NOT NULL,
);

CREATE TABLE FACTURA (
    ID_FACTURA INT NOT NULL,
	ID_TARJETAHB INT NOT NULL,
    REGISTRO INT NOT NULL,
    FECHA_EXP DATETIME NOT NULL     
);

CREATE TABLE CATEGORIA_VEHICULO (
    ID_CATEGORIAVH INT NOT NULL,
	ID_TARIFA INT NOT NULL,
    CAT_DESCRIPCION VARCHAR(40) NOT NULL
);

CREATE TABLE VEHICULO (
    PLACA VARCHAR(15) NOT NULL,
	ID_CATEGORIAVH INT NOT NULL,
    MODELO INT NOT NULL,
    MARCA VARCHAR(30) NOT NULL,
    COLOR VARCHAR(20) NOT NULL  
);

CREATE TABLE MOVIMIENTO_PEAJE_FACTURA_VEHICULO (
    ID_FACTURA INT NOT NULL,
    ID_PEAJE  INT NOT NULL,
	PLACA VARCHAR(15) NOT NULL,
	SUBTOTAL INT NOT NULL,
	IVA INT NOT NULL,
	TOTAL INT NOT NULL
);


-- CLAVES PRIMARIAS
ALTER TABLE PEAJE
ADD CONSTRAINT PK_PEAJE PRIMARY KEY (ID_PEAJE)

ALTER TABLE USUARIO
ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)

ALTER TABLE TARIFA
ADD CONSTRAINT PK_TARIFA PRIMARY KEY (ID_TARIFA)

ALTER TABLE TARJETAHB
ADD CONSTRAINT PK_TARJETAHB PRIMARY KEY (ID_TARJETAHB)

ALTER TABLE FACTURA
ADD CONSTRAINT PK_FACTURA PRIMARY KEY (ID_FACTURA)

ALTER TABLE CATEGORIA_VEHICULO
ADD CONSTRAINT PK_CATEGORIA_VEHICULO PRIMARY KEY (ID_CATEGORIAVH)

ALTER TABLE VEHICULO
ADD CONSTRAINT PK_VEHICULO PRIMARY KEY (PLACA)

-- CLAVE COMPUESTA
ALTER TABLE MOVIMIENTO_PEAJE_FACTURA_VEHICULO
ADD CONSTRAINT PK_MOVIMIENTO_PEAJE_FACTURA_VEHICULO PRIMARY KEY (ID_FACTURA,ID_PEAJE,PLACA)

-- LLAVES FORANEAS
ALTER TABLE TARJETAHB
ADD CONSTRAINT FK_USUARIO_TARJETAHB_ FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE FACTURA
ADD CONSTRAINT FK_TARJETAHB_FACTURA FOREIGN KEY (ID_TARJETAHB) REFERENCES TARJETAHB(ID_TARJETAHB)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE CATEGORIA_VEHICULO
ADD CONSTRAINT FK_TARIFA_CATEGORIA_VEHICULO FOREIGN KEY (ID_TARIFA) REFERENCES TARIFA(ID_TARIFA)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE VEHICULO
ADD CONSTRAINT FK_CATEGORIA_VEHICULO_VEHICULO FOREIGN KEY (ID_CATEGORIAVH) REFERENCES CATEGORIA_VEHICULO(ID_CATEGORIAVH)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE MOVIMIENTO_PEAJE_FACTURA_VEHICULO
ADD CONSTRAINT FK_FACTURA_MOVIMIENTO_PEAJE_FACTURA_VEHICULO FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE MOVIMIENTO_PEAJE_FACTURA_VEHICULO
ADD CONSTRAINT FK_PEAJE_MOVIMIENTO_PEAJE_FACTURA_VEHICULO FOREIGN KEY (ID_PEAJE) REFERENCES PEAJE(ID_PEAJE)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE MOVIMIENTO_PEAJE_FACTURA_VEHICULO
ADD CONSTRAINT FK_VEHICULO_MOVIMIENTO_PEAJE_FACTURA_VEHICULO FOREIGN KEY (PLACA) REFERENCES VEHICULO(PLACA)
ON DELETE CASCADE
ON UPDATE CASCADE

--------------------- PROCESOS ALMACENADOS ----------------------------------------

--- REGISTRAR PEAJE ---

CREATE PROCEDURE REGISTRAR_PEAJE
    @ID_PEAJE INT,
    @NOMBRE_PEAJE VARCHAR(40),
    @UBICACION VARCHAR(30),
    @TEL_PEAJE INT,
    @CORREO_PEAJE VARCHAR(30),
    @NIT VARCHAR(30)
AS
BEGIN
    INSERT INTO PEAJE (ID_PEAJE, NOMBRE_PEAJE, UBICACION, TEL_PEAJE, CORREO_PEAJE, NIT)
    VALUES (@ID_PEAJE, @NOMBRE_PEAJE, @UBICACION, @TEL_PEAJE, @CORREO_PEAJE, @NIT);
END;
    
-- ACTUALIZAR REGISTRO DE PEAJE
CREATE PROCEDURE ACTUALIZAR_PEAJE
    @ID_PEAJE INT,
    @NOMBRE_PEAJE VARCHAR(40),
    @UBICACION VARCHAR(30),
    @TEL_PEAJE INT,
    @CORREO_PEAJE VARCHAR(30),
    @NIT VARCHAR(30)
AS
BEGIN
    UPDATE PEAJE
    SET NOMBRE_PEAJE = @NOMBRE_PEAJE, UBICACION = @UBICACION, TEL_PEAJE = @TEL_PEAJE, CORREO_PEAJE = @CORREO_PEAJE, NIT = @NIT
    WHERE ID_PEAJE = @ID_PEAJE;
END;

-- ELIMINAR PEAJE
CREATE PROCEDURE ELIMINAR_PEAJE
    @ID_PEAJE INT
AS
BEGIN
    DELETE FROM PEAJE WHERE ID_PEAJE = @ID_PEAJE;
END;

-- LISTAR PEAJE POR ID
CREATE PROCEDURE LISTAR_PEAJE
    @ID_PEAJE INT
AS
BEGIN
    SELECT * FROM PEAJE WHERE ID_PEAJE = @ID_PEAJE;
END;

--PRUEBAS
EXECUTE REGISTRAR_PEAJE '001','CARIMAGUA','NARIÑO','4444444','PEAJECARIMAGUA@GMAIL.COM','0000000-1'
EXECUTE ACTUALIZAR_PEAJE '001','CARIMAGUA','NARIÑO','4444446','PEAJECARIMAGUA@GMAIL.COM','0000001-1'
SELECT * FROM PEAJE
EXECUTE LISTAR_PEAJE '001'
EXECUTE ELIMINAR_PEAJE '001'

-------------------------------------------------------------------------------------------------------------------

-- REGISTRAR TARJETAHB ---

CREATE PROCEDURE REGISTRO_TARJETAHB
    @ID_TARJETAHB INT,
	@ID_USUARIO INT,
    @FECHA_EXP DATETIME,
	@MODOS_RECARGA VARCHAR(30),
    @SALDO INT	
AS
BEGIN
    INSERT INTO TARJETAHB (ID_TARJETAHB, ID_USUARIO, FECHA_EXP, MODOS_RECARGA, SALDO)
    VALUES (@ID_TARJETAHB, @ID_USUARIO, @FECHA_EXP, @MODOS_RECARGA, @SALDO);
END;


-- ACTUALIZAR REGISTRO DE TARJETAHB
CREATE PROCEDURE ACTUALIZAR_TARJETAHB
    @ID_TARJETAHB INT,
	@ID_USUARIO INT,
    @FECHA_EXP DATETIME,
	@MODOS_RECARGA VARCHAR(30),
    @SALDO INT	
AS
BEGIN
    UPDATE TARJETAHB
    SET ID_USUARIO = @ID_USUARIO, FECHA_EXP = @FECHA_EXP, MODOS_RECARGA = @MODOS_RECARGA, SALDO = @SALDO 
    WHERE ID_TARJETAHB = @ID_TARJETAHB;
END;


--P.A ELIMINAR TARJETAHB
CREATE PROCEDURE ELIMINAR_TARJETAHB
    @ID_TARJETAHB INT
AS
BEGIN
    DELETE FROM TARJETAHB
    WHERE ID_TARJETAHB = @ID_TARJETAHB;
END;


--P.A LISTAR TARJETASHB
CREATE PROCEDURE LISTAR_TARJETASHB
AS
BEGIN
    SELECT * FROM TARJETAHB;
END;

--P.A LISTAR TARJETAHB POR ID
CREATE PROCEDURE LISTAR_TARJETAHB_ID
    @ID_TARJETAHB INT
AS
BEGIN
    SELECT * FROM TARJETAHB
    WHERE ID_TARJETAHB = @ID_TARJETAHB;
END;

--PRUEBAS
--EXECUTE REGISTRO_TARJETAHB '1','1','08-06-2024','PSE','10000'
--SELECT * FROM USUARIO
--EXECUTE ACTUALIZAR_TARJETAHB '1','1','08-06-2024','TARJETA CREDITO','60000'
--EXECUTE LISTAR_TARJETASHB
--EXECUTE ELIMINAR_TARJETAHB '1'
--EXECUTE LISTAR_TARJETAHB_ID '1'
--SELECT * FROM TARJETAHB

---------------------------------------------------------------------------------------------- REGISTRAR USUARIO

CREATE PROCEDURE REGISTRAR_USUARIO
    @ID_USUARIO INT,
    @NOMBRES_USUARIO VARCHAR(30),
    @APELLIDOS_USUARIO VARCHAR(30),
	@CEDULA INT,
    @FECHA_NACIMIENTO DATE,
    @DIRECCION VARCHAR(30),
    @CORREO VARCHAR(40),
    @PASSWORD NVARCHAR(50),
    @ROL VARCHAR(30)
AS
BEGIN
    INSERT INTO USUARIO (ID_USUARIO, NOMBRES_USUARIO, APELLIDOS_USUARIO, CEDULA, FECHA_NACIMIENTO, DIRECCION, CORREO, PASSWORD, ROL)
    VALUES (@ID_USUARIO, @NOMBRES_USUARIO, @APELLIDOS_USUARIO, @CEDULA, @FECHA_NACIMIENTO, @DIRECCION, @CORREO, @PASSWORD, @ROL);
END;

-- ACTUALIZAR REGISTRO DE USUARIO
CREATE PROCEDURE ACTUALIZAR_USUARIO
    @ID_USUARIO INT,
    @NOMBRES_USUARIO VARCHAR(30),
    @APELLIDOS_USUARIO VARCHAR(30),
	@CEDULA INT,
    @FECHA_NACIMIENTO DATE,
    @DIRECCION VARCHAR(30),
    @CORREO VARCHAR(40),
    @PASSWORD NVARCHAR(50),
	@ROL VARCHAR(30)
AS
BEGIN
    UPDATE USUARIO
    SET NOMBRES_USUARIO = @NOMBRES_USUARIO, APELLIDOS_USUARIO = @APELLIDOS_USUARIO, CEDULA = @CEDULA, FECHA_NACIMIENTO = @FECHA_NACIMIENTO,
        DIRECCION = @DIRECCION, CORREO = @CORREO, PASSWORD = @PASSWORD, ROL = @ROL
    WHERE ID_USUARIO = @ID_USUARIO;
END;


-- ELIMINAR USUARIO
CREATE PROCEDURE ELIMINAR_USUARIO
    @ID_USUARIO INT
AS
BEGIN
    DELETE FROM USUARIO WHERE ID_USUARIO = @ID_USUARIO;
END;


-- LISTAR USUARIOS
CREATE PROCEDURE LISTAR_USUARIOS
AS
BEGIN
    SELECT * FROM USUARIO;
END;


-- LISTAR USUARIO POR ID
CREATE PROCEDURE LISTAR_USUARIO
    @ID_USUARIO INT
AS
BEGIN
    SELECT * FROM USUARIO WHERE ID_USUARIO = @ID_USUARIO;
END;


--PRUEBAS
--EXECUTE REGISTRAR_USUARIO '11','José David','Arciniegas Molano','1130605081','1985-02-24','CLL 60 No.107-71','josedav100@hotmail.com','@rc1n13g@s2024*','CLIENTE'
--EXECUTE ACTUALIZAR_USUARIO '11','José David','Arciniegas Molano','1130605083','1985-02-25','CLL 60 No.107-71','josedavid100@hotmail.com','@rc1n13g@s2024*','CLIENTE'
--SELECT * FROM USUARIO
--EXECUTE LISTAR_USUARIOS
--EXECUTE LISTAR_USUARIO '1'
--EXECUTE ELIMINAR_USUARIO '11'

-------------------------------------------------------------------------------------------------------------------------------

-- REGISTRAR FACTURA
CREATE PROCEDURE REGISTRAR_FACTURA
    @ID_FACTURA INT,
	@ID_TARJETAHB INT,
    @REGISTRO INT,
    @FECHA_EXP DATETIME  
AS
BEGIN
    INSERT INTO FACTURA (ID_FACTURA, ID_TARJETAHB, REGISTRO, FECHA_EXP)
    VALUES (@ID_FACTURA, @ID_TARJETAHB, @REGISTRO,@FECHA_EXP);
END;


-- ACTUALIZAR REGISTRO DE FACTURA
CREATE PROCEDURE ACTUALIZAR_FACTURA
    @ID_FACTURA INT,
	@ID_TARJETAHB INT,
    @REGISTRO INT,
    @FECHA_EXP DATETIME
AS
BEGIN
    UPDATE FACTURA
    SET ID_TARJETAHB = @ID_TARJETAHB, REGISTRO = @REGISTRO, FECHA_EXP = @FECHA_EXP
    WHERE ID_FACTURA = @ID_FACTURA;
END;


--P.A ELIMINAR FACTURA
CREATE PROCEDURE ELIMINAR_FACTURA
    @ID_FACTURA INT
AS
BEGIN
    DELETE FROM FACTURA
    WHERE ID_FACTURA = @ID_FACTURA;
END


--P.A LISTAR FACTURAS
CREATE PROCEDURE LISTAR_FACTURA
AS
BEGIN
    SELECT * FROM FACTURA;
END;


--P.A LISTAR FACTURA POR ID
CREATE PROCEDURE LISTAR_FACTURA_ID
    @ID_FACTURA INT
AS
BEGIN
    SELECT * FROM FACTURA
    WHERE ID_FACTURA = @ID_FACTURA;
END;


--PRUEBAS
--EXECUTE REGISTRAR_FACTURA '1','1','1','2024-06-08'
--EXECUTE ACTUALIZAR_FACTURA '1','1','2','2024-06-08'
--EXECUTE LISTAR_FACTURA_ID '1'
--EXECUTE LISTAR_FACTURA
--EXECUTE ELIMINAR_FACTURA '1'
--SELECT * FROM FACTURA

---------------------------------------------------------------------------------------------------------------------------------

-- REGISTRO DE TARIFAS
CREATE PROCEDURE REGISTRO_TARIFA
	@ID_TARIFA INT,
	@MONTO_TARIFA INT,
    @TRF_DESCRIPCION VARCHAR(40)
AS
BEGIN
    INSERT INTO TARIFA(ID_TARIFA, MONTO_TARIFA, TRF_DESCRIPCION)
    VALUES (@ID_TARIFA, @MONTO_TARIFA, @TRF_DESCRIPCION);
END;


-- ACTUALIZAR REGISTRO DE TARIFAS
CREATE PROCEDURE ACTUALIZAR_TARIFA
    @ID_TARIFA INT,
	@MONTO_TARIFA INT,
    @TRF_DESCRIPCION VARCHAR(40)
AS
BEGIN
    UPDATE TARIFA
    SET MONTO_TARIFA = @MONTO_TARIFA, TRF_DESCRIPCION = @TRF_DESCRIPCION
    WHERE ID_TARIFA = @ID_TARIFA;
END;


-- ELIMINAR TARIFA
CREATE PROCEDURE ELIMINAR_TARIFA
    @ID_TARIFA INT
AS
BEGIN
    DELETE FROM TARIFA
    WHERE ID_TARIFA = @ID_TARIFA;
END;


-- LISTAR TARIFAS
CREATE PROCEDURE LISTAR_TARIFAS
AS
BEGIN
    SELECT * FROM TARIFA;
END;


-- LISTAR TARIFA POR ID
CREATE PROCEDURE LISTAR_TARIFA_ID
    @ID_TARIFA INT
AS
BEGIN
    SELECT * FROM TARIFA
    WHERE ID_TARIFA = @ID_TARIFA;
END;


--PRUEBAS
--EXECUTE REGISTRO_TARIFA '1','10000','TARIFA1'
--EXECUTE ACTUALIZAR_TARIFA'1','20000','TARIFA1'
--EXECUTE ELIMINAR_TARIFA '2'
--EXECUTE LISTAR_TARIFA_ID '1'
--EXECUTE LISTAR_TARIFAS
--SELECT * FROM TARIFA

---------------------------------------------------------------------------------------------------------------------

-- REGISTRO CATEGORIA DE VEHICULOS
CREATE PROCEDURE REGISTRO_CATEGORIA_VEHICULO
    @ID_CATEGORIAVH INT,
	@ID_TARIFA INT,
    @CAT_DESCRIPCION VARCHAR(40)
AS
BEGIN
    INSERT INTO CATEGORIA_VEHICULO (ID_CATEGORIAVH, ID_TARIFA, CAT_DESCRIPCION)
    VALUES (@ID_CATEGORIAVH, @ID_TARIFA, @CAT_DESCRIPCION);
END;



-- ACTUALIZAR REGISTRO DEL VEHICULO
CREATE PROCEDURE ACTUALIZAR_CATEGORIA_VEHICULO
    @ID_CATEGORIAVH INT,
	@ID_TARIFA INT,
    @CAT_DESCRIPCION VARCHAR(40)
	
AS
BEGIN
    UPDATE CATEGORIA_VEHICULO
    SET ID_TARIFA = @ID_TARIFA, CAT_DESCRIPCION = @CAT_DESCRIPCION  
    WHERE ID_CATEGORIAVH = @ID_CATEGORIAVH;
END;


-- ELIMINAR CATEGORIA DE VEHICULO
CREATE PROCEDURE ELIMINAR_CATEGORIA_VEHICULO
    @ID_CATEGORIAVH INT
AS
BEGIN
    DELETE FROM CATEGORIA_VEHICULO
    WHERE ID_CATEGORIAVH = @ID_CATEGORIAVH;
END;


-- LISTAR CATEGORIAS DE VEHICULOS
CREATE PROCEDURE LISTAR_CATEGORIAS
AS
BEGIN
    SELECT * FROM CATEGORIA_VEHICULO;
END;


-- LISTAR CATEGORIA DE VEHICULO POR ID
CREATE PROCEDURE LISTAR_CATEGORIA_ID
    @ID_CATEGORIAVH INT
AS
BEGIN
    SELECT * FROM CATEGORIA_VEHICULO
    WHERE ID_CATEGORIAVH = @ID_CATEGORIAVH;
END;


--PRUEBAS
EXECUTE REGISTRO_CATEGORIA_VEHICULO '1','1','AUTOMOVILES,CAMPEROS,CAMOONETAS'
EXECUTE ACTUALIZAR_CATEGORIA_VEHICULO '1','1','AUTOMOVILES-CAMPERO-CAMIONETAS'
EXECUTE ELIMINAR_CATEGORIA_VEHICULO '11'
EXECUTE LISTAR_CATEGORIA_ID '1'
EXECUTE LISTAR_CATEGORIAS
SELECT * FROM CATEGORIA_VEHICULO

------------------------------------------------------------------------------------------------------------------

-- REGISTRAR VEHICULO
CREATE PROCEDURE REGISTRAR_VEHICULO
    @PLACA VARCHAR(15),
	@ID_CATEGORIAVH INT,
    @MODELO VARCHAR(20),
    @MARCA VARCHAR(30),
    @COLOR VARCHAR(20)	
AS
BEGIN
    INSERT INTO VEHICULO (PLACA, ID_CATEGORIAVH, MODELO, MARCA, COLOR)
    VALUES (@PLACA, @ID_CATEGORIAVH, @MODELO, @MARCA, @COLOR);
END;


-- ACTUALIZAR REGISTRO DE VEHICULO
CREATE PROCEDURE ACTUALIZAR_VEHICULO
    @PLACA VARCHAR(15),
	@ID_CATEGORIAVH INT,
    @MODELO VARCHAR(20),
    @MARCA VARCHAR(30),
    @COLOR VARCHAR(20)
AS
BEGIN
    UPDATE VEHICULO
    SET ID_CATEGORIAVH = @ID_CATEGORIAVH, MODELO = @MODELO,MARCA = @MARCA,COLOR = @COLOR
    WHERE PLACA = @PLACA;
END;


-- ELIMINAR VEHICULO
CREATE PROCEDURE ELIMINAR_VEHICULO
    @PLACA VARCHAR(15)
AS
BEGIN
    DELETE FROM VEHICULO
    WHERE PLACA = @PLACA;
END;


-- LISTAR VEHICULOS
CREATE PROCEDURE LISTAR_VEHICULOS
AS
BEGIN
    SELECT * FROM VEHICULO;
END;


-- LISTAR VEHICULO POR PLACA
CREATE PROCEDURE LISTAR_VEHICULO_PLACA
    @PLACA VARCHAR(15)
AS
BEGIN
    SELECT * FROM VEHICULO
    WHERE PLACA = @PLACA;
END;


--PRUEBAS
--EXECUTE REGISTRAR_VEHICULO 'ZJD65C','1','2006','HONDA','ROJONEGRO'
--EXECUTE ACTUALIZAR_VEHICULO 'ZJD65C','1','2005','HONDA','ROJO'
--EXECUTE LISTAR_VEHICULOS
--EXECUTE LISTAR_VEHICULO_PLACA 'ZJD65C'
--EXECUTE ELIMINAR_VEHICULO 'ZJD65C'
--SELECT * FROM VEHICULO

-------------------------------------------------------------------------------------------------------------------

-- REGISTRO_MOVIMIENTO_PEAJE_FACTURA_VEHICULO
CREATE PROCEDURE REGISTRO_MOVIMIENTO_PEAJE_FACTURA_VEHICULO
	@ID_FACTURA INT,
	@ID_PEAJE INT,
    @PLACA VARCHAR(15),
	@SUBTOTAL INT,
	@IVA INT,
	@TOTAL INT
AS
BEGIN
    INSERT INTO MOVIMIENTO_PEAJE_FACTURA_VEHICULO(ID_FACTURA, ID_PEAJE, PLACA, SUBTOTAL, IVA, TOTAL)
    VALUES (@ID_FACTURA, @ID_PEAJE, @PLACA, @SUBTOTAL, @IVA, @TOTAL);
END;

-- ACTUALIZAR REGISTRO MOVIMIENTO_PEAJE_FACTURA_VEHICULO 
CREATE PROCEDURE ACTUALIZAR_MOVIMIENTO_PEAJE_FACTURA_VEHICULO
    @ID_FACTURA INT,
	@ID_PEAJE INT,
    @PLACA VARCHAR(15),
	@SUBTOTAL INT,
	@IVA INT,
	@TOTAL INT
AS
BEGIN
    UPDATE MOVIMIENTO_PEAJE_FACTURA_VEHICULO
    SET SUBTOTAL = @SUBTOTAL, IVA = @IVA, TOTAL = @TOTAL 
    WHERE ID_FACTURA = @ID_FACTURA AND ID_PEAJE = @ID_PEAJE AND PLACA = @PLACA;
END;



--P.A ELIMINAR TARIFA MOVIMIENTO_PEAJE_FACTURA_VEHICULO
CREATE PROCEDURE ELIMINAR_MOVIMIENTO_PEAJE_FACTURA_VEHICULO
    @ID_FACTURA INT,
	@ID_PEAJE INT,
    @PLACA VARCHAR(15)
AS
BEGIN
    DELETE FROM MOVIMIENTO_PEAJE_FACTURA_VEHICULO
    WHERE  ID_FACTURA = @ID_FACTURA AND ID_PEAJE = @ID_PEAJE AND PLACA = @PLACA;
END;


--P.A LISTAR TARIFAS MOVIMIENTO_PEAJE_FACTURA_VEHICULO
CREATE PROCEDURE LISTAR_MOVIMIENTO_PEAJE_FACTURA_VEHICULO
AS
BEGIN
    SELECT * FROM MOVIMIENTO_PEAJE_FACTURA_VEHICULO;
END;


--P.A LISTAR MOVIMIENTO_PEAJE_FACTURA_VEHICULO POR ID
CREATE PROCEDURE LISTAR_MOVIMIENTO_PEAJE_FACTURA_VEHICULO_ID
    @ID_FACTURA INT,
	@ID_PEAJE INT,
    @PLACA VARCHAR(15)
AS
BEGIN
    SELECT * FROM MOVIMIENTO_PEAJE_FACTURA_VEHICULO
    WHERE  ID_FACTURA = @ID_FACTURA AND ID_PEAJE = @ID_PEAJE AND PLACA = @PLACA;
END;

SELECT * FROM PEAJE

--EXECUTE REGISTRO_MOVIMIENTO_PEAJE_FACTURA_VEHICULO '1','1','ZJD65C','1985','15','2000'
--EXECUTE ACTUALIZAR_MOVIMIENTO_PEAJE_FACTURA_VEHICULO '1','1','ZJD65C','1980','0','1980' --En Colombia, la tarifa de peajes está exenta del Impuesto al Valor Agregado (IVA
--EXECUTE LISTAR_MOVIMIENTO_PEAJE_FACTURA_VEHICULO
--EXECUTE LISTAR_MOVIMIENTO_PEAJE_FACTURA_VEHICULO_ID '1','1','ZJD65C'
--EXECUTE ELIMINAR_MOVIMIENTO_PEAJE_FACTURA_VEHICULO '1','1','ZJD65C'
--SELECT * FROM MOVIMIENTO_PEAJE_FACTURA_VEHICULO